language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t greshmashaji/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true greshmashaji/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-113937505928'
  bucket_path: 'docker-react'
  on: 
    branch: master
  access_key_id: $AWS-ACCESS-KEY
  secret_access_key: 
    secure: "$AWS-SECRET-KEY"


  